# Generated by Django 3.1.2 on 2021-07-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='comment',
            field=models.CharField(max_length=500, verbose_name='コメント'),
        ),
    ]
