# Generated by Django 3.1.2 on 2021-07-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_topic_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='無題', max_length=20, verbose_name='タイトル'),
        ),
    ]
